version: '3'
services:
  web:
    build:
      context: ./app
    environment:
      RACK_ENV: development
      VIRTUAL_HOST: localhost
    ports:
      - "8080:8080"
  scheduler:
    build:
      context: ./app
    environment:
      RACK_ENV: development
