CREATE TABLE dbo.Product 
(
		ProductID INT NOT NULL IDENTITY (301,1) PRIMARY KEY,
		ProductName Nvarchar(100) NOT NULL,
		Number INT NOT NULL,
		Price MONEY NOT NULL,
	    SysStart datetime2 (0) GENERATED ALWAYS AS ROW START NOT NULL,
		SysEnd datetime2 (0) GENERATED ALWAYS AS ROW END NOT NULL,
		PERIOD FOR SYSTEM_TIME (SysStart, SysEnd)

		)
		WITH (SYSTEM_VERSIONING = ON (HISTORY_TABLE = dbo.ProdHistory));
		GO

--QUERIES THE TABLE TO DISPLAY INFORMATION ABOUT HOW THE PRODUCT PRICES HAVE CHANGED IN THE LAST TWO HOURS--

SELECT ProductId, Price, SysStart
FROM dbo.Products
FOR SYSTEM_TIME FROM DATEADD(hh,-2,GETDATE()) TO GETDATE()
